# Generated by Django 6.0.3 on 2026-03-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_content_about_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='hero_image_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
