# Generated by Django 6.0.3 on 2026-03-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_content_hero_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='hero_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
