# Generated by Django 6.0.3 on 2026-03-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_content_hero_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='hero_image_url',
        ),
        migrations.RemoveField(
            model_name='content',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='content',
            name='image_url',
            field=models.URLField(default='binkhan', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='binkhan', max_length=255),
            preserve_default=False,
        ),
    ]
