# Generated by Django 6.0.3 on 2026-03-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_content_hero_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image_url',
            field=models.ImageField(upload_to='content/', verbose_name='Image'),
        ),
    ]
