# Generated by Django 6.0.3 on 2026-03-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_content_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image_url',
            field=models.ImageField(upload_to='content/'),
        ),
    ]
