# Generated by Django 6.0.3 on 2026-03-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_news_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image_url',
            field=models.ImageField(max_length=5000, upload_to='content/'),
        ),
    ]
