# Generated by Django 6.0.3 on 2026-03-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_content_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='content/'),
        ),
    ]
