# Generated by Django 6.0.3 on 2026-03-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_news_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identifier for the stat (e.g., students, teachers)', unique=True)),
                ('number', models.CharField(help_text='Example: 500+, 100%, 50+', max_length=50)),
                ('label_en', models.CharField(help_text='Label in English', max_length=100)),
                ('label_bn', models.CharField(help_text='Label in Bengali', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Institution Stat',
                'verbose_name_plural': 'Institution Stats',
                'ordering': ['order'],
            },
        ),
    ]
