# Generated by Django 6.0.3 on 2026-03-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_institutionstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='teachers/', verbose_name='Teacher Photo')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('name_bn', models.CharField(max_length=255, verbose_name='Name (Bangla)')),
                ('role_en', models.CharField(max_length=255, verbose_name='Role (English)')),
                ('role_bn', models.CharField(max_length=255, verbose_name='Role (Bangla)')),
                ('bio_en', models.TextField(verbose_name='Bio (English)')),
                ('bio_bn', models.TextField(verbose_name='Bio (Bangla)')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
