# Generated by Django 6.0.3 on 2026-03-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Event Photo')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_bn', models.CharField(max_length=255, verbose_name='Title (Bangla)')),
                ('date_en', models.CharField(max_length=100, verbose_name='Date (English)')),
                ('date_bn', models.CharField(max_length=100, verbose_name='Date (Bangla)')),
                ('time_en', models.CharField(max_length=100, verbose_name='Time (English)')),
                ('time_bn', models.CharField(max_length=100, verbose_name='Time (Bangla)')),
                ('location_en', models.CharField(max_length=255, verbose_name='Location (English)')),
                ('location_bn', models.CharField(max_length=255, verbose_name='Location (Bangla)')),
                ('desc_en', models.TextField(verbose_name='Description (English)')),
                ('desc_bn', models.TextField(verbose_name='Description (Bangla)')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
