# Generated by Django 6.0.3 on 2026-03-11 18:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
