# Generated by Django 6.0.3 on 2026-03-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_event_image_alter_teacher_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='image',
            new_name='image_url',
        ),
    ]
