# Generated by Django 6.0.3 on 2026-03-12 11:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_image_event_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
