# Generated by Django 6.0.3 on 2026-03-31 20:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_event_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload Video (mp4, etc.)', max_length=255, null=True, verbose_name='video'),
        ),
    ]
